<a href="https://colab.research.google.com/github/Bougriba/Machine-learning-Models-Implementation/blob/main/SVR%2BdecisionTreeRegressor%2BRandomforestTreeRegressor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
dataset = pd.read_csv('Data.csv')
dataset

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   AT      9568 non-null   float64
 1   V       9568 non-null   float64
 2   AP      9568 non-null   float64
 3   RH      9568 non-null   float64
 4   PE      9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB


In [ ]:
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [ ]:
y=y.reshape(len(y),1)

In [ ]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train = sc_X.fit_transform(X_train)
y_train = sc_y.fit_transform(y_train)

In [ ]:
from sklearn.svm import SVR
regressor = SVR(kernel='rbf')
regressor.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [ ]:
y_pred = sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[456.98 458.96]
 [463.67 463.29]
 [437.52 435.27]
 ...
 [476.33 476.22]
 [432.91 440.29]
 [464.26 467.92]]


In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9479978713795594

In [ ]:
X_train=sc_X.inverse_transform(X_train)

In [ ]:
y_train=sc_y.inverse_transform(y_train)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
regressor_tree=DecisionTreeRegressor(random_state=0)
regressor_tree.fit(X_train,y_train)

DecisionTreeRegressor(random_state=0)

In [ ]:
y_pred_tree=regressor_tree.predict(X_test)

In [ ]:
np.set_printoptions(precision=2)
print(np.concatenate ( ( y_pred_tree.reshape(len(y_pred_tree),1),y_test.reshape(len(y_test),1) ),1))

[[459.65 458.96]
 [462.26 463.29]
 [436.03 435.27]
 ...
 [477.18 476.22]
 [432.78 440.29]
 [468.23 467.92]]


In [ ]:
r2_score(y_test, y_pred_tree)

0.9342783714449767

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor_RandomForest=RandomForestRegressor(n_estimators=10,random_state=0)
regressor_RandomForest.fit(X_train,y_train)

<ipython-input-35-e77ae727a282>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regressor_RandomForest.fit(X_train,y_train)


RandomForestRegressor(n_estimators=10, random_state=0)

In [ ]:
y_pred_randomforest=regressor_RandomForest.predict(X_test)

In [ ]:
np.set_printoptions(precision=2)
print(np.concatenate ( ( y_pred_randomforest.reshape(len(y_pred_randomforest),1),y_test.reshape(len(y_test),1) ),1))

[[457.9  458.96]
 [464.07 463.29]
 [439.72 435.27]
 ...
 [476.18 476.22]
 [432.9  440.29]
 [466.11 467.92]]


In [ ]:
r2_score(y_test, y_pred_randomforest)

0.9628673278135129